version: '3'

services:
  redis:
    image: redis
    restart: always
    volumes:
      - redis_projetao:/data
  
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: superset
      POSTGRES_PASSWORD: superset
      POSTGRES_USER: superset
    volumes:
      - postgres_projetao:/var/lib/postgresql/data
  
  superset:
    image: amancevice/superset
    restart: always
    depends_on:
      - postgres
      - redis
    links: 
      - postgres
      - redis
    environment:
      MAPBOX_API_KEY: ${MAPBOX_API_KEY}
    ports:
      - "8088:8088"
    volumes:
      - ./superset/superset_config.py:/etc/superset/superset_config.py

  notebook:
    build: 
      context: ./notebook
    container_name: note_projetao
    ports:
      - "8888:8888"
    volumes:
      - ./notebook:/notebook/
    links: 
      - postgres
    command: jupyter notebook --ip=0.0.0.0 --port=8888 --allow-root

volumes:
  postgres_projetao:
  redis_projetao: